import Footer from '@/components/footer/footer'
import './globals.css'
import NavBar from '@/components/navbar/navbar'

import { Inter, Poppins, Roboto } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: '400'
})


const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500']
})

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['100', '300']
})


export const metadata = {
  title: 'woxro',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} ${roboto.variable}`} >
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
